//arc.hash,arc.output.ast_printer,arc.stringtable,arc.syntax.ast,arc.syntax.lexer,arc.syntax.location,arc.syntax.parser,arc.syntax.parser_tests,arc.syntax.syntax_reporter
//Automatically generated by unit_threaded.gen_ut_main, do not edit by hand.
import unit_threaded;

int main(string[] args)
{
    return args.runTests!(
                          "arc.hash",
                          "arc.output.ast_printer",
                          "arc.stringtable",
                          "arc.syntax.ast",
                          "arc.syntax.lexer",
                          "arc.syntax.location",
                          "arc.syntax.parser",
                          "arc.syntax.parser_tests",
                          "arc.syntax.syntax_reporter"
                          );
}
